// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYt-E1Y1SBVw0Db4_E3YHr67yWZHssQ9o',
    appId: '1:836610347710:web:2c92a039f566cb4b2f84ef',
    messagingSenderId: '836610347710',
    projectId: 'basic-user-71480',
    authDomain: 'basic-user-71480.firebaseapp.com',
    storageBucket: 'basic-user-71480.appspot.com',
    measurementId: 'G-LW7143M9S3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgbptIiBd2M7gLkiD2el2fJWaM8fgfBis',
    appId: '1:836610347710:android:040af1902a781c762f84ef',
    messagingSenderId: '836610347710',
    projectId: 'basic-user-71480',
    storageBucket: 'basic-user-71480.appspot.com',
  );
}
